---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: fulleim
description: All EIM API services enabled
services:
  - RegionService
  - SiteService
  - LocationService
  - HostService
  - OperatingSystemService
  - InstanceService
  - ScheduleService
  - WorkloadService
  - WorkloadMemberService
  - ProviderService
  - TelemetryLogsGroupService
  - TelemetryMetricsGroupService
  - TelemetryMetricsProfileService
  - TelemetryLogsProfileService
  - LocalAccountService
  - CustomConfigService
  - OSUpdatePolicyService
  - OSUpdateRunService
