services:
  - RegionService
  - SiteService
  - LocationService
  - HostService
  - OperatingSystemService
  - InstanceService
  - ScheduleService
  - WorkloadService
  - WorkloadMemberService
  - ProviderService
  - TelemetryLogsGroupService
  - TelemetryMetricsGroupService
  - TelemetryMetricsProfileService
  - TelemetryLogsProfileService
  - LocalAccountService
  - CustomConfigService
  - OSUpdatePolicyService
  - OSUpdateRunService